name = "meetgest-api"
main = "src/index.ts"
compatibility_date = "2025-05-28"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "meetgest-db"
database_id = "92e4f516-33a5-47ac-b6a4-9fef90094448"

[vars]
LANGFUSE_HOST = "https://jp.cloud.langfuse.com"
OPENROUTER_MODEL = "meta-llama/llama-3.3-70b-instruct:free"
ANTHROPIC_MODEL = "claude-haiku-4-5-20251001"
